[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://type-beat-backend-x2x4tp5wra-uc.a.run.app"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
